// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: import_of_legacy_library_into_null_safe
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  //static const FirebaseOptions web = FirebaseOptions(googleAppID: 'Ummah2U');
  static const FirebaseOptions web = FirebaseOptions(
    googleAppID: 'Ummah2U',
    apiKey: 'AIzaSyBkSmy-QRZ5a8H1OHtntJ8ON_vlRsakSrE',
    // appId: '1:369580567004:web:7b71fc02b5d214c3278719',
    // messagingSenderId: '369580567004',
    // projectId: 'platinum-trees-373300',
    // authDomain: 'platinum-trees-373300.firebaseapp.com',
    storageBucket: 'platinum-trees-373300.appspot.com',
    // measurementId: 'G-C97M7EVWGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    googleAppID: 'Ummah2U',
    apiKey: 'AIzaSyDc_4QEp0dex2XN1NbV-q4-ziIyxVm9y84',
    // appId: '1:369580567004:android:e757904aabb46bfe278719',
    // messagingSenderId: '369580567004',
    // projectId: 'platinum-trees-373300',
    storageBucket: 'platinum-trees-373300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    googleAppID: 'Ummah2U',
    apiKey: 'AIzaSyCODl7lnpJ2KAl012vypsd16uUK1V-aQ1A',
    // appId: '1:369580567004:ios:57ce436a8e170fb4278719',
    // messagingSenderId: '369580567004',
    // projectId: 'platinum-trees-373300',
    storageBucket: 'platinum-trees-373300.appspot.com',
    // iosClientId:
    //     '369580567004-4n09j0lk20pq6q28kvd6c6m9rhia660i.apps.googleusercontent.com',
    // iosBundleId: 'com.example.myUmmah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    googleAppID: 'Ummah2U',
    apiKey: 'AIzaSyCODl7lnpJ2KAl012vypsd16uUK1V-aQ1A',
    // appId: '1:369580567004:ios:57ce436a8e170fb4278719',
    // messagingSenderId: '369580567004',
    // projectId: 'platinum-trees-373300',
    storageBucket: 'platinum-trees-373300.appspot.com',
    // iosClientId:
    //     '369580567004-4n09j0lk20pq6q28kvd6c6m9rhia660i.apps.googleusercontent.com',
    // iosBundleId: 'com.example.myUmmah',
  );
}
